### ISSUE TITLE
Arduino Board CAD

### ISSUE THREAD

**Issue by jessicamd** [FRCTeam3206/Electrical#15]
For the 5/23 meeting we started to CAD the board, we will continue on next meeting and try to start constructing the board. Pneumatics for the sub-board need to be gathered and discussed. Also, an IO expander and CAN shield should arrive shortly. Red and yellow LEDs have arrived, green will be ordered. We have the power supply and will reuse the polycarbonate.

**Comment by RajGandhi** [comment]
Merged this issue with existing Arduino Controller Board issue.
